### ISSUE TITLE
Feature: Filter incidents by source system type

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#108]
We need to be able to make notification filters based on source type (just all navs). I suggest reusing tag-filters, by sending tags of the type `source_system_type=nav`. (Or maybe `source_type=nav`?)

Later, it would be useful to filter the table on source type as well.

See https://github.com/Uninett/Argus/issues/117 for relevant backend issue.

**Comment by katsel** [comment]
Filtering by tag has been implemented into Argus. Does this resolve this issue?

**Comment by katsel** [comment]
Corresponding open backend issue is Uninett/Argus#177.
