### ISSUE TITLE
User names on Acks and Events are missing from the Incident details modal

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#122]
The acknowledgement and event lists in the Incident details modal only display the integer user id, which is opaque and useless for an end user. These components should both **display user names**.

ATM, user data is not inlined by the API endpoints used to fetch event logs and incident acknowledgements, so that the user details need to be fetched from the `/api/v1/auth/users/<int:pk>/` endpoint.

However, it is reasonable to assume that the username is always interesting for most consumers of the API, so we should post a corresponding issue for the backend to inline these details in the mentioned endpoints.

**Comment by hmpf** [comment]
The version currently in "production" does show usernames for acknowledgments and events.
