### ISSUE TITLE
Polish: The error-message from 400 Bad Request aren't shown to the enduser

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#124]
The backend frequently sends a json-body with its 400 Bad Request-replies. It is better UX to show these than only "400 Bad Request" when something breaks. (It also speeds up debugging!)

**Comment by jorgenbele** [comment]
I agree that there should be a way to make the json bodies easily available to users. The current use of snackbars will have to change slightly in order for this to be possible, so how do you suggest it should be done?

If there was a button "more info" on the error alert, then we could make it open a modal presenting the json body to the user.

**Comment by podliashanyk** [comment]
Related issue on backend [#304](https://github.com/Uninett/Argus/issues/304)
