### ISSUE TITLE
Polish: Either hide the pagination stuff in the incident list, or implement it

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#131]

**Comment by jorgenbele** [comment]
Are the required features implemented in the backend? If so then the pagination system should be changed to fetch a single page because a sizable amount of effort has been spent on making this component compatible with proper pagination.

**Comment by hmpf** [comment]
We haven't decided on what form of pagination we want yet. Makes implementing rather tricky :)
