### ISSUE TITLE
Use consistent DateTimes

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#137]
The datepicker for setting an ack's expiry date is hardcoded to US dates.
It is hard-coded to MM/dd/yyyy. It should use whatever the locale uses. (Preferably by something looking up the locale's date-format and storing it in a variable so that it can be overridden by the members of the Church of ISO 8601 later =) )

**Comment by hmpf** [comment]
We might very well wait with fixing this, much less in your face than other annoyances.

**Comment by katsel** [comment]
It's desirable to use a consistent DateTime format throughout the frontend.

It would be nice to have a global setting for this, but for now hard-coding it to ISODate should suffice.
