### ISSUE TITLE
Allow a permanent filter on the incident list per user

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#149]
See https://github.com/Uninett/Argus/issues/170

"incident list": the front page, basically.

**Comment by katsel** [comment]
Picking up @vidarstokke's idea here #173:

> make ~~filters~~ notification profiles visible on the front page
> allow users to choose a default ~~filter~~ notification profile so that this filter is active as soon as they log in to Argus

(Let's use notification profiles not filters, as profiles are more powerful and easier to persist.)

One issue with this is, that

- the front page is currently including ALL incidents, and filters will narrow this down
- the notification system is defined to include NO incidents, unless they have explicitly been included via filters

This is making it difficult for the users to understand what filters are for, and what their notification profiles will do.

There is some work needed here to make the behaviour consistent. Ideas:

1. Either the front page should have no incidents, until the users define a notification profile with filters defining what to include. (So front page matches notification profile behaviour.) **OR:**
2. A notification profile with no filters should have ALL incidents, filters narrow it down. (So it matches the front page's behaviour.)
**OR:**
3. We settle to make a clearer distinction between front page and notification profiles. (And make this visible and obvious to the user, as this is counterintuitive.)

A compromise building on 1.) might be to add some default notification profiles to Argus, for example "show all". Then apply this profile to the start page by default (allowing users to change this for a user-defined profile).

This issue directly relates to Uninett/Argus#170: (filter on incident list per-user), Uninett/Argus#220 (handling notification profiles with no filter), Uninett/Argus#177 (adding exclusive filters to the front page?) as well as the whole re-design of the Notification system (https://github.com/Uninett/Argus/milestone/4) and the corresponding frontend issues.

**Comment by hmpf** [comment]
> Picking up @vidarstokke's idea here #173:
> 
> > make ~filters~ notification profiles visible on the front page
> > allow users to choose a default ~filter~ notification profile so that this filter is active as soon as they log in to Argus
> 
> (Let's use notification profiles not filters, as profiles are more powerful and easier to persist.)

A notification profile is a set of filters given a cvollective name and added to a single timeslot, so let's not.

I don't think it is possible to have two timeslots both covering 24/7 belonging to two different notification profiles.

(There's a reason the milestone ["New notification system"](https://github.com/Uninett/Argus/milestone/4) exists, so far with 7 issues.)

**Comment by hmpf** [comment]
Suggestions for fixes:

>     1. The front page has no incidents, until the users define a notification profile with filters defining what to include. (= "Front page matches notification profile behaviour" solution) **OR:**

End-user says: "This thing is broken! No incidents!"

>     2. A notification profile with no filters should have ALL incidents, filters narrow it down. ("Notification profile matches front page's behaviour" solution)

Yep, the self-DoS solution and the way NAV does it. IIRC one of the main reasons for Argus existing is because NAV does filtering/notifications badly.

>     3. We settle to make a clearer distinction between front page and notification profiles. And make this visible and obvious to the user, as this is counterintuitive. ("Front page and notification profile are separate" solution)

+1

> A compromise building on 1.) might be to add some **default notification profiles** to Argus, for example "show all". Then apply this profile to the start page by default (allowing users to change this for a user-defined profile later).

Needs to work better than my "Everything"-filter since that needs updating whenever we add a source.

**Comment by katsel** [comment]
> A notification profile is a set of filters given a collective name and added to a single timeslot, so let's not.
>
> I don't think it is possible to have two timeslots both covering 24/7 belonging to two different notification profiles.

Thanks for clarifying!

A data structure that allows grouping of filters, and no time slot attached, would seem quite useful to me. (For exactly such things as viewing the front page.)

But agreed, this issue might not be the right place to discuss it.

**Comment by hmpf** [comment]
Currently, NotificationProfile has a non-nullable foreign key to timeslot (one to one key). Every user has an automatically generated "All the time" timeslot, and this can only have one profile.

This ensures that a timeslot can only be used once. If NotificationProfile had an ordinary FK to Timeslot there would be no support in the db to detect duplicates. We could turn it around and have the timeslot have a one to one to the profile, then a profile wouldn't need a timeslot.

**Comment by hmpf** [comment]
> A data structure that allows grouping of filters, and no time slot attached, would seem quite useful to me. (For exactly such things as viewing the front page.)

.. yes, since a NotificationProfile is also the place to hook up a phone-number (and later hook up one or more email addresses and other so called notification *media*, I think a notion of a "set of filters" not having anything to do with notifications is needed. (I need to double check if there can be one or more filters per existing profile..) Then a profile would have  fk to such a set and the front page could use the set directly. Or something. (Yes, I frequently think by writing something down.)

Though, logically, I don't think we need a notion of a *set* of filters. We should avoid the need for [Karnaugh maps](https://en.wikipedia.org/wiki/Karnaugh_map) and [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) that NAV has. Though, a set of filters always being a union.. hm, hm..

**Comment by katsel** [comment]
> Currently, NotificationProfile has a non-nullable foreign key to timeslot (one to one key). Every user has an automatically generated "All the time" timeslot, and this can only have one profile.

In the current data model, the timeslots are unique by **name**, not by actual time duration.
A user can add timeslot "All time 1" ranging Day 1-7, 0:00:00 - 23:59:59,999, then "All time 2" with the same span, and so on. The API will allow this, as long as the names are different.
This behaviour is neither sensible nor expected, so the data model may need work anyway.

**Comment by katsel** [comment]
Interestingly, `pk` for the new timeslot is incremented with every unsuccessful try to add a timeslot with a preexisting name.
One timeslot in the DB, `pk`: 1.
Add a timeslot, fail because of non-unique name.
Add one more timeslot that also fails.
Add timeslot, and if successful, it will have a `pk` of 4 (expected: 2).

Not to digress too much here. Do we have a place to collect such oddities about the Argus data model and API?

**Comment by hmpf** [comment]
Blue sky:

Combine the filter creation page and the landing page so that filters are created on the landing page and can be used both for notifications and the incident list.

**Comment by katsel** [comment]
Closing in favour of #173 , which makes the idea clearer.
