### ISSUE TITLE
Oddness: why does IncidentMetadata need to exist?

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#159]
IncidentMetadata fetches from the endpoint `/api/v1/incidents/metadata/`:

```
{
    "sourceSystems": [
        {
            "pk": 1,
            "name": "argus",
            "type": {
                "name": "argus"
            },
            "user": 1,
            "base_url": ""
        }
}
```

which is almost identical to the endpoint `/api/v1/incidents/sources/` except that the latter you need to be logged in for and it is not hidden in a an object/dict:

```
[
   {
      "pk": 1,
      "name": "argus",
      "type": {
          "name": "argus"
      },
      "user": 1,
      "base_url": ""
   }
]
```

In IncidentView, (if I read things correctly) this metadata is used to map what I guess is source pks to source names, but you can do that with the structure above just as well. Ditto in FiltersView, and that is the only place this is used.

It looks to me like that endpoint is redundant. Worse, it is written in such a way that it is not possible to automatically create an OpenApi 3 schema for it (see PR https://github.com/Uninett/Argus/pull/185).

**Comment by lunkwill42** [comment]
It seems thhe **undocumented** endpoint `incidents/sources` may also be *redundant*.

The necessary information about an Incident's source is, AFAICT, inlined in each Incident record from the `incidents` endpoint. That is, unless you actually the the name of the Source System's user as well, and not just the user PK.

The Source System's `pk`, `name`, `type`, `user` (int) and `base_url` are inlined.

**Comment by jorgenbele** [comment]
Frontend needs to have access to a list of source systems with names and PKs so that it can be presented in the filtering components. The metadata endpoint is currently used to provide autocompletion on source system names. We could just use the inlined information in the incidents retrieved from the API, but that would probably not include incidents from all source systems in most cases.

As to why it exists, i don't know, but this is the way it's being used.

**Comment by hmpf** [comment]
It should be trivial to switch to using `incident/sources` through, for 1.1.

**Comment by jorgenbele** [comment]
Closing this as there has not been any new discussion in months.
