### ISSUE TITLE
"Sources to display" filtered choices not shown

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#167]
**Describe the bug**
In the Incidents view in Argus. When choosing one or more sources in "Sources to display", the filtering will become active and thereby listing only incidents from that source, but the sources chosen will not become listed in the "Sources to display" field. So it is not possible to see the sources I have selected and not possible to remove any sources to display. 

**To Reproduce**
1. Go to 'Main page of Argus'
2. Click on 'Sources to display'
3. Select one source, ie. uninav.uninett.no
4. Then the incidents from only uninav.uninett.no will be displayed, but the sources selected in "Sources to display" is still empty. 

**Expected behavior**
When selecting a source, it should show that source in the field "Sources to display". Just like it did before and just like in the "Tags filter" field. 

**Screenshots**
Selecting a source:
![image](https://user-images.githubusercontent.com/73838355/98351107-8fe11c80-201c-11eb-96b2-4bd39e9b4f70.png)
After selecting "uninav.uninett.no", it should display that source in the field "Source to display", but it doesn't. 
![image](https://user-images.githubusercontent.com/73838355/98351171-a4251980-201c-11eb-8cc1-6cc27699974a.png)

Expected behavior is it is in the "Tags filter" field:
![image](https://user-images.githubusercontent.com/73838355/98351306-d171c780-201c-11eb-88aa-ea24abb4aedf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested on both Chrome and Firefox. 
 - Version Chrome Version 86.0.4240.111

**Comment by Wiggen94** [comment]
This worked fine earlier today. This also makes the filter feature unusable with multiple filters as only the last chosen filter is in use.

**Comment by jorgenbele** [comment]
I can confirm that the bug exists (or existed) on the version used in production at the date of this issues creation. It has been fixed in a wip branch, which hopefully can be merged soon.
