### ISSUE TITLE
Have a drop down menu on the front page to select an existing filter

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#173]
There will potentially be a lot of alerts in Argus. A nice way to limit the number of alarms is by filters. But currently filters are only possible to tie up with notification profiles. 

Is it possible to make filters visible on the front page and maybe also make me choose a default filter on my user so that this filter is active as soon as I log in to Argus?

**Comment by hmpf** [comment]
Duplicate, see #149 and https://github.com/Uninett/Argus/issues/170

**Comment by hmpf** [comment]
Blue sky:

Combine the filter creation page and the landing page so that filters are created on the landing page and can be used both for notifications and the incident list.

**Comment by katsel** [comment]
Doable for now:

- The ability to select a default filter for the front page.

Long-term goal:
- Redesign notification profiles, with a possible option to store the front page filters inside a "front page" notification profile. Or similar.

**Comment by katsel** [comment]
Quote @hmpf, #204 

> Send the primary key of the filter as a GET-parameter. Depends on Uninett/Argus#244

**Comment by hmpf** [comment]
From #244:

> Security consideration here: If submitting a PK to a filter that does not belong to the current user, that should be an error

Obviously, the dropdown should only have the filters of the logged-in user.
