### ISSUE TITLE
Frontend needs end-user documentation, user manual

### ISSUE THREAD

**Issue by katsel** [Uninett/Argus-frontend#174]
## Current situation

Argus(-backend) so far has

- deployment docs
- developer docs
- API docs

## What's missing

End-user docs detailing the use of the frontend I cannot find anywhere.

## Objective

User docs explain concepts, show usage examples and address frequently asked questions, thus providing the end user with an overall better experience.

Also, design decisions can be manifested here. ("We do not support feature X, and this is why -- but hey you can try Z instead!")

Many issues can be prevented by showing users how you expect them to use your software, and where its limitations are.

Hence, user doc is not just a good thing to have, it's a priority.

**Comment by lunkwill42** [comment]
This has been flagged as a priority by Géant as well.
