### ISSUE TITLE
BUG: Important parts of login screen not visible and unreachable

### ISSUE THREAD

**Issue by kbarmen** [Uninett/Argus-frontend#202]
**Important parts of login screen not visible and unreachable**

When using a small screen device (like a smaller phone), a smaller web browser window, or using a large font, or zooming in, the bottom part of the login screen vanishes out of sight. In addition, there is stylesheet present that not only hides any scrollbars - the primary visual sign that there is more content on a page than what is visible - scrolling seems to be disabled fully. So when the bottom part of the page is not visible, there is no way of figuring that Feide-login even exists on this page.

Also, the very logo of the app suffers from stylesheets, the S in ARGUS is hidden, so it looks more like ARGU.

**To Reproduce**
1. Go to 'argus.uninett.no' (notice how the S in ARGUS is mostly hidden)
2. Press ctrl+ to zoom in, or use a larger font, or make browser window smaller
3. Scroll down to 'Login with Feide'... 
4. See error - you can not scroll down to 'Login with Feide'

**Expected behavior**
I expect at least to see scrollbars that indicate that there is content outside of visible area of a web page.

**Screenshots**
<img width="864" alt="image" src="https://user-images.githubusercontent.com/30319643/103513300-9cda8a80-4e6a-11eb-8657-d8b10af85e2e.png">

**Comment by hmpf** [comment]
Good report, thx!
