### ISSUE TITLE
Persist incident page size between app reloads

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#208]
The default page size for incidents is currently 10 (which, IMHO, is optimistically low). I can select among various other page sizes from a dropdown. However, my selection is not persisted when I reload the entire app, which is quite annoying.

**Feature request**
Persist the user's choice of page size into their browser's local storage. This way, I will always have a predictable page size.

**Comment by katsel** [comment]
Please also

- [ ] increase default incident size to 20 or 25

**Comment by lunkwill42** [comment]
Actually, this might become obsolete, as @jorgenbele is working to replace paging with infinite scroll, I think..

**Comment by jorgenbele** [comment]
> Actually, this might become obsolete, as @jorgenbele is working to replace paging with infinite scroll, I think..
> 
> If you have a PR or issue reference, please add it here..

I have only planned on using infinite scroll when realtime is used, keeping paging when interval/never is used.
