### ISSUE TITLE
Could it be possible to pick 24-hour timestamps. 

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#212]
Today it is only possible to pick timestamps with PM/AM. It is confusing for us with 24-hour heads. Could it be possible to choose 24-hour in our account?

**Comment by jorgenbele** [comment]
#214 adds the possibility to toggle between AMPM and 24H clock time pickers in the configuration. In the future it might be useful to allow the users themselves to set it. It could be stored in local storage quite easily.

**Comment by katsel** [comment]
Does this touch on #137 too, maybe?

**Comment by hmpf** [comment]
This needs support in the backend. It might not be necessary to change the API at all, just how datetime ranges are looked up when checking whether to send a notification.

**Comment by hmpf** [comment]
Hm, misunderstood what this ticket is about. It *is* possible to set timestamps with 24h clocks in the frontend now, what is not possible is setting a timestamp that goes past 24h. Closing, making new tickets for this other problem.
