### ISSUE TITLE
Make version numbers visible

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#215]
Make the version number of the backend, and frontend, visible somehow.

---

I think the best place to put it is at the bottom, so we get

> Argus server v1.2.3, frontend v.4.5.6-c0ffee78. Last refreshed 09:37:25, updating in real time

Final decision for placement is up to the implementer.

Without getting too deeply into versioning discussion, I suggest using the branch name/commit hash where there is no canonical version available.
/kat

**Comment by hmpf** [comment]
See also https://github.com/Uninett/Argus/issues/254

**Comment by katsel** [comment]
The task cannot be completed until Uninett/Argus#254 is finished, so this is currently blocked.

**Comment by hmpf** [comment]
This is three tasks: 

* Backend version
* Frontend version
* API version
