### ISSUE TITLE
Sources filter on front page is not applied to new incidents when using Auto Update.

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#217]
**Describe the bug**
In Argus frontpage, when Argus is updated with new incidents and you have a Sources filter applied, then it seems that new incidents are not filtered. For instance with the screen shot example, where incidents from uninav and lokalnav are shown even though the Sources only includes sias-vk, khio-vk and unit-vk. This is because these Incidents have occurred after I applied these filters. 

**To Reproduce**
1. Go to Argus frontend
2. Apply a filter in 'Sources' for instance only 'khio-vk.c.uninett.no'
3. Wait for an incident appearing from another source, for instance 'sias-vk, uninav, lokalnav, unit-vk'. 
4. Observe that this incident occurs in the list of incidents. 

**Expected behavior**
I expect that new incidents also gets filtered based on the Sources or Tags selected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73838355/105174827-6a47b780-5b23-11eb-983e-5180b0024118.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by jorgenbele** [comment]
Do you have realtime enabled? If so this is the same as #200.

**Comment by vidarstokke** [comment]
Yes it is with realtime enabled. I thought I saw this behaviour with Interval as well, but I am not able to reproduce.
