### ISSUE TITLE
The possibilities to update multiple events at the same time.

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#222]
It would have been really nice to update multiple events with the same data at the same time. 

For instance if I need to set similar Acknowledgement on or close multiple events with the same message, I today need to go in to the events one at a time and update it. Then it would have been good to be able to doing this in one action.

**Comment by jorgenbele** [comment]
I already started on implementing this feature last summer. Then I added another column to the incidents table where you can select incidents, and the table header shows several actions (acknowledge, close, etc.) that will be done to all of them. 

How often do you want to do this? Would it make sense to always have this extra column visible or should that be an setting you can change? (under additional settings in toolbar for example). In the latter case, do you think it should be default on, or default off?

**Comment by vidarstokke** [comment]
I think that the column could always be there.

**Comment by jorgenbele** [comment]
Closing because it was solved in #232
