### ISSUE TITLE
Bug: When the backend cannot be reached (network problem) nothing sensible is shown

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#237]
**Describe the bug**
If the frontend cannot access the backend after login, either everything hangs with no form of alert, or an "Unhandled Rejection" pops up.

**To Reproduce**
1. Log in to a frontend that uses a backend (via BACKEND_URL) that can be easily shut off, like for instance localhost 
2. Turn off the backend
3. See problem (attached screenshot)

**Expected behavior**
Show some error-message that explains that the backend is unreachable.

**Screenshots**

Automated error: counter (1 of 5) slowly increases if "interval" is on.
![image](https://user-images.githubusercontent.com/11956096/108476925-e2280f80-7292-11eb-9ea6-96f3f4b7c4bd.png)

If we click that away:
![image](https://user-images.githubusercontent.com/11956096/108477182-30d5a980-7293-11eb-8d0c-08acf2bf49af.png)

**Additional context**
If the backend is unreachable prior to/during login, the browser itself will complain, so no need to cover that angle.

**Comment by jorgenbele** [comment]
Closing, because it was solved in #239
