### ISSUE TITLE
Bug: Blank page when visiting incident details dialog on Safari

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#257]
**Describe the bug**
The incident details dialog doesn't work on Safari. Clicking on any incident (or any incident permalink) returns a blank page. In addition, using the back button doesn't work, the blank page remains.

**To Reproduce**
1. Browse the Argus frontend
2. Click on any incident
3. See blank page

**Expected behavior**
Expect to to see the same incident details dialog as on other browsers.

**Screenshots**
![Screenshot 2021-05-10 at 09 52 06](https://user-images.githubusercontent.com/100995/117624678-7361a080-b175-11eb-8d1a-c8d50f7dea99.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Browser: Safari 14.0.3

**Comment by podliashanyk** [comment]
This bug is caused by the same reason as issue #261
