### ISSUE TITLE
Bug: Acknowledgements do not appear after creation

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#260]
**Describe the bug**
If I acknowledge an Incident, the acknowledgment is never displayed in the incident dialog until I close it and re-open it

**To Reproduce**
1. Click on any unacknowledged incident
2. Click on 'Create acknowledgement'
3. Fill inn a comment and click 'Submit'
4. See the popup message about the ack being submitted to the backend
5. Observe that the list of acknowledgements in the dialog box remains empty
6. Close the dialog box
7. Find the incident in the incident list again and click it (your filter must inlude acked incidents)
8. Observe that the acknowledgement is now there

**Expected behavior**
An acknowledgement should appear immediately in the dialog box as soon as the backend has accepted it.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: master (70284a347b6166004b990f08229822fd3ae1b2c2)

**Comment by hermar98** [comment]
After PR #268 this works as expected. Closing issue.
