### ISSUE TITLE
Idea: Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by katsel** [Uninett/Argus-frontend#262]
A contributors' guide to Argus and Argus-frontend has been under discussion for a while now, and I finally found the time to collect and write down my thoughts on the subject.
I hope this can be useful.

## Motivation

A contributors' guide (commonly as a `CONTRIBUTING.md` file) is an excellent means of communicating about an open source code/software project asynchronously. Such a contributor's guide can be essential for attracting new developers to a project. By telling potential new developers how to approach the project, it will lower the threshold for making meaningful contributions. As such, it can both reduce the amount of time required to 'onboard' new developers on a project, and reduce the effort for existing developers who receive such contributions. It will also ensure the original developers' main ideas, intentions and principles are documented and can be followed as development goes forward in time.
A contributors' guide is an asset to any open source project.

## Objective

The objective of a `CONTRIBUTING.md` can be anything the developer/s find/s useful to know. A good `CONTRIBUTING.md` is clear and concise in language, and communicates expectations in a straight-forward and friendly manner. It tries to make as few assumptions about the new contributor as possible (besides that they do have *some* technical experience on the subject, but are likely not an expert).

Usually, it will contain clear and beginner-friendly instructions on subjects like
- How to install dependencies and set-up a development environment for the project
- What the project parts are and where they are located (on a files and directory level)
- How to run automated tests and how to conduct manual testing (what to pay attention to, what is likely to break)
- General notes on development, such as coding principles followed, upgrade routines, style guidelines and editor settings
- Typical development "gotchas" for this project (if any)
- How to make a very good pull request

## Notable examples

Angular-translate Project: https://github.com/angular-translate/angular-translate/blob/master/CONTRIBUTING.md
PurpleBooth README template https://github.com/PurpleBooth/a-good-readme-template/blob/main/CONTRIBUTING.md
Rust project https://rustc-dev-guide.rust-lang.org/contributing.html#contributing-to-rust
and many more

**Comment by lunkwill42** [comment]
Ideally, I would assign this to @jorgenbele to draft a first version of this before our summer interns show up to work on the frontend in June :)

**Comment by lunkwill42** [comment]
@jorgenbele added a baseline in 5cd66577f8431eaa14109e42e77027e6dca8dbef - I would like the summer interns to follow up on it :)

**Comment by hmpf** [comment]
See [CONTRIBUTING.org](https://github.com/Uninett/Argus-frontend/blob/master/CONTRIBUTING.org) for a good start.
