### ISSUE TITLE
Set ticket url as a bulk operation

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#265]
Today it is only possible to add a ticket ID to an incident by clicking the incident and adding it. 

I would like to be able to put the same ticket ID on multiple incidents the same way as it is possible to ACK multiple incidents at the same time. 

![image](https://user-images.githubusercontent.com/73838355/122397627-6e182280-cf79-11eb-9b6c-68fcfc21f1ad.png)

**Comment by lunkwill42** [comment]
The API has no support for bulk operations. However, the bulk "Ack" and bulk "Close/re-open" functionality in the frontend is already built to issue requests in bulk. I am therefore going to assumed this code can be partially re-used to make a bulk "add ticket url" function as well.
