### ISSUE TITLE
Bug: incomplete logout when using several tabs

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Argus-frontend#322]
**Describe the bug**
When Argus is running in several tabs in the browser, logout in one of them does not trigger the logged out state in the rest of the tabs. 
API calls can be performed in all tabs, where logout was not performed explicitly. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to /incidents
2. Open /timeslots in a new tab
3. Perform logout in the /incidents tab
4. Perform any update on a timeslot in the /timeslots tab
5. See the update in the /timeslots tab being successfully performed

**Expected behavior**
Logout from Argus should trigger logout in all tabs running Argus with a given cookie.

**Comment by hmpf** [comment]
Possibly connected to #79
