### ISSUE TITLE
Bug: Tags filter only hides filtered incidents, counter messed up

### ISSUE THREAD

**Issue by stveit** [Uninett/Argus-frontend#324]
**Describe the bug**
Filtering incidents using the Tags filter hides the filtered incidents, but they still occupy space on the page.
So if 6 incidents on a page are filtered out using tags, a page can state that it contains 10 incidents, but only show the 4 that are not filtered out.

**To Reproduce**
1. Go to https://argus.uninett.no/
2. Set tags to something
3. Browse through the pages and observe the number of entries per page vs stated rows-per-page

**Expected behavior**
The pages should fill up with incidents matching the filter. 
The incidents that are filtered out should not occupy space on the page, they should instead be replaced with the next incidents that match the filter.

**Screenshots**
Screenshot with no Tags used. 10 incidents are shown in the page (Rows per page=10). Two of these entries have the tag room=ifi2.

![not-tags](https://user-images.githubusercontent.com/31960753/130781753-f8052438-ac8f-4d62-937a-e4fea071b074.png)

Screenshot with tags used. Only  the two incidents from the first screenshot that match the tags filter is included on the first page, even though it states that it shows 10 entries.
![tags](https://user-images.githubusercontent.com/31960753/130782000-0383fd2d-80f9-446a-adf4-9572b03b992e.png)

The second page shows 7 entries, showing that the 2 on the first page are not the only ones matching the filter

![image](https://user-images.githubusercontent.com/31960753/130782214-c49ff3e8-6087-4ae7-a25c-d5972f210548.png)

**Desktop:**
 - OS: Ubuntu 20.04.2
 - Browser Firefox 
 - Version 91.0

**Comment by podliashanyk** [comment]
Additional bug detail based on workaround that Service Center uses: switching to 100 rows per page leads to several more incidents being displayed.
