### ISSUE TITLE
Add support for multiple email addresses per person

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#330]
See https://github.com/Uninett/Argus/issues/322.

Users will need to be able to add and change email-addresses, except for auto-filled addresses. Also, notification profiles must choose at least one of a set of multiple email addresses. Much of the phone number handling could be used as a template for how to do this.

Opinion: Something that might improve the UX is to, instead of having one field for "Media", one for "Phone number" and one for "Email address", have a single field that combines media and and what that media needs, this will also easily allow for sending to multiple phone numbers and email addresses in one go:

["SMS:99009900", "SMS:44004400", "Email:247@example.com"]

**Comment by podliashanyk** [comment]
Fixed in #475, #479 and #492
