### ISSUE TITLE
Bug: "Open State = BOTH" and "Acked = BOTH" combined with filters gives fishy incident list

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#336]
**Describe the bug**
When I use filters (either Tags or Sources) and combine this with "Open State = BOTH" and "Acked = BOTH", there is something fishy going on in the incident list. If I also have "Rows per page: 100", the frontend will not display 100 incidents that match the filter, but a lot less. To get more incidents that match the filter, I need to go to the next page. 

**To Reproduce**
1. Select Open State = BOTH
2. Select Acked = BOTH
3. Select Tags = "kundetjeneste=Campus_CNaaS" and "organization=uninett". 
4. Select Max level = 5
5. Select Timeframe = No timeframe

This will currently give a list of 6 items. But at the bottom line it says "1-100 of more than 100". You will have to go to next page to get the next items matching the filters. 

**Expected behavior**
I would like to see 100 incidents matching the filters and not only 6. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73838355/135587604-17d05b9b-2b47-4742-bde9-97cb1429906e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 93.0.4577.82

**Comment by podliashanyk** [comment]
This issue is related to #324

**Comment by lunkwill42** [comment]
Closed by #346
