### ISSUE TITLE
Make it impossible to delete a filter that is in use in a notification profile

### ISSUE THREAD

**Issue by vidarstokke** [Uninett/Argus-frontend#337]
I've experienced (the hard way), that deleting a filter that is use in a notification profile can cause the notifications to stop. 

So my suggestion is to make it impossible to delete a filter when it is used in a notification profile. Give a warning and say that the notification profile needs to use another filter before deleting the filter that you want to delete.

**Comment by hmpf** [comment]
This also needs backend-support: delete a used filter, get an error, which the frontend can then show.

**Comment by johannaengland** [comment]
Closed by Uninett/Argus#392
