### ISSUE TITLE
Bug: Cannot log in after logging out when using dataporten/feide

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#340]
Something odd happens when I log out of argus (frontend 1.5.2). 
I don't get the login-window at all, and can no longer log in. When not using containers (for instance via safe mode or private window) it works fine.

The load goes through the roof and I need to restart firefox.

This has been verified to happen on Firefox (91.0.2) both with and without containers, as well as Vivaldi 4.1.x. A workaround to be able to log back in is to manually get rid of the cookie for the domain.

See video:

https://user-images.githubusercontent.com/11956096/139822193-5151b362-f3d7-4d75-b79c-e93a7232f1d9.mp4

**Comment by runborg** [comment]
I've also stumbled on this issue, but i'm not using tab-containers but are using socks proxy and normal firefox browser

**Comment by hmpf** [comment]
It seems I cannot reproduce this on Vivaldi 4.1.x.

**Comment by lunkwill42** [comment]
Everything works for me until I log out. Then it enters into an infite loop with these error messages.

Clearing cookies and site data stops the issue, and I can log in again. Same thing occurs when I log out again.

This is reproducible for me with containers (incidental) on Firefox, but also on Safari (no containers there)

**Comment by lunkwill42** [comment]
I'd like to add that this only occurs when logging in using Feide authentication, not when using local user accounts.

**Comment by podliashanyk** [comment]
Bug is finally reproduced in dev. @hmpf, @lunkwill42 thank you for help with the setup!
Starting to work on the fix

**Comment by hmpf** [comment]
Correct me if I'm wrong @podliashanyk but it seems that in prod, the backend sets a cookie named "token" on a domain the frontend can read, then the frontend sets the same cookie, secure and with a different domain. When logging out, the frontend cookie is removed, the token stored in the backend is removed, but the backend cookie is **not** removed.

So there are several questions:

* Why does the frontend need to set the cookie at all
* If the frontend does need to set it, why the same name
* The backend needs to remove its own cookie also
* Why does the backend set an insecure cookie while the frontend sets a secure cookie?

I think answering these questions might be enough to fix this problem, but it might be necessary for the backend to also erase additional cookies so that the redirect to dataporten works next time.

The real problem I guess is that we use a cookie for this at all, and that the frontend knows about how the backend talks to feide. We have the issue #302 and #303 about this already, I'll jot down my current thoughts in #302.

**Comment by hmpf** [comment]
https://github.com/Uninett/Argus/pull/323 has the backend remove the cookie it set itself.
