### ISSUE TITLE
Bug: Page blanks out when selecting a predefined filter

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#349]
**Describe the bug**

In my profile in the production version of Argus, I have several predefined filters. As I open the Argus front page, everything looks fine. As soon as I select one of my predefined filters from the dropdown list, the entire page blanks out (the lattice background image is all that remains).

**To Reproduce**
1. Browse an Argus instance (in my case, it's our production instance)
2. Click on the "Filter" dropdown
3. Click on one of your predefined filters
4. See blank page

**Expected behavior**
The settings stored in the filter should be made visible in the filter form, and the list of matching incidents should be updated accordingly.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1 Monterey
 - Browser: Firefox 96 (Same result in Safari 15.1)
 - Argus frontend version: 1.5.4
 - Argus backend version: 1.3.4

**Additional context**

Another user reports that they do not get a blank page when selecting a pre-defined filter. The filter appears to activate correctly. However, the filter settings for *Source* and *Tags* are **not displayed**.

In my case, selecting a predefined filter throws the following errors in the browser console:

```
TypeError: Me is undefined
    T useAutocomplete.js:935
    N Autocomplete.js:386
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 20
    274 index.tsx:9
    f (index):1
    232 main.a2ae390a.chunk.js:1
    f (index):1
    t (index):1
    r (index):1
    <anonymous> main.a2ae390a.chunk.js:1
react_devtools_backend.js:4045:25
```

```
Uncaught TypeError: Me is undefined
    T useAutocomplete.js:935
    N Autocomplete.js:386
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 20
    274 index.tsx:9
    f (index):1
    232 main.a2ae390a.chunk.js:1
    f (index):1
    t (index):1
    r (index):1
    <anonymous> main.a2ae390a.chunk.js:1
useAutocomplete.js:935:2
```

**Comment by podliashanyk** [comment]
### Update:

#346 introduced changes to the filter object. Bug appears only for filters that are created before 16.12.2021.
**In Firefox, Chrome, and others:** page blanks out.
**In Safari:** page does not blank out, but filter parameters of _Source_ and _Tags_ are not displayed.
