### ISSUE TITLE
Add button in incident view to open a new issue in ticket system

### ISSUE THREAD

**Issue by johannaengland** [Uninett/Argus-frontend#396]
https://github.com/Uninett/Argus/issues/474 introduces an endpoint to get an url to a created issue in an issue system. 

This endpoint should be used to add a button to the incident view to open this link in a new tab and show any errors that might happen.

**Comment by johannaengland** [comment]
Yes, but only when https://github.com/Uninett/Argus/issues/460 is merged

**Comment by podliashanyk** [comment]
Uninett/Argus#516 adds base ticket integration. Frontend needs to implement changes accordingly.

After IRL conversation with @johannaengland:

- Argus frontend does not need to be concerned about which ticket plugin the user is utilising, POST endpoint is same for all the ticket systems
