### ISSUE TITLE
Let user create destinations in settings

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Argus-frontend#416]
Inspired by #357.

Notification profiles in API v2 use _destinations_ instead of _media_. 
Frontend needs to introduce the notion of _destinations_, and let user configure their destinations.

Destinations supported by backend so far are emails and phone numbers.

**Comment by podliashanyk** [comment]
Is blocked until [Uninett/Argus#478](https://github.com/Uninett/Argus/pull/478) is merged.

**Comment by hmpf** [comment]
Both [Uninett/Argus#478](https://github.com/Uninett/Argus/pull/478) and [Uninett/Argus#480](https://github.com/Uninett/Argus/pull/480) have been merged.

**Comment by lunkwill42** [comment]
Fixed by #492 , #479 and #475
