### ISSUE TITLE
Bug: Frontend updates notifprofiles using DELETE + POST

### ISSUE THREAD

**Issue by stveit** [Uninett/Argus-frontend#445]
When updating notification profiles, the frontend deletes the existing one and creates a new one. Instead it should just
use the PUT method.

**Comment by stveit** [comment]
Sometimes it uses PUT, sometimes it used POST + DELETE

**Comment by podliashanyk** [comment]
Was about to report this one as well. It uses delete when some of the values are invalid, f.e. when user selects media _SMS_ and phone number _None_.

**Comment by podliashanyk** [comment]
POST + DELETE are used only when user updates timeslot in a profile.
PUT is used when user updates anything else in a profile.
