### ISSUE TITLE
Misleading error message on login screen when frontend cannot connect to backend

### ISSUE THREAD

**Issue by stveit** [Uninett/Argus-frontend#451]
When trying to log in while there is no backend to connect to this is shown:

![image](https://user-images.githubusercontent.com/31960753/195854433-20fe19f5-e1d2-4efe-b06c-0da2a8e73cf9.png)

An error message indicating that it couldnt connect to Argus or something like that might be better than to make the user 
think that their credentials are wrong.

**Comment by lunkwill42** [comment]
I agree, this is just stupid, and it's already hitting users who are trying out Argus for the first time. 

See https://lists.geant.org/sympa/arc/argus-users/2023-02/msg00003.html for reference. In this case, there is a problem with missing CORS headers from the backend, so the web browsers is blocking the requests to the back-end - but the error message reported to the user is still _"Wrong username or password"._
