### ISSUE TITLE
Incident level is not saved in filter

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#454]
Not sure if this is a bug or a feature request.

We need to go through what should be put in notification filters right now since the backend has added a lot of filterable stuff, like event type.

**Comment by podliashanyk** [comment]
@hmpf Could not reproduce it. I get to persist severity level when saving/modifying a filter

**Comment by hmpf** [comment]
On save in frontend, a filter currently contains:

* sourceSystemId
* tags
* open
* acked
* event_type
* maxlevel

Old filters do not contain all these.
