### ISSUE TITLE
Bug: Couldn't login in Argus frontend

### ISSUE THREAD

**Issue by mhmdawnallah** [Uninett/Argus-frontend#497]
I'm running the Argus front end from the latest version in the master branch in development mode. The first page I got is the login page and I entered `admin`  and `admin` for username and password respectively and got a `Wrong username or password` error message. I've also debugged the Network console and I've found an issue related to `CORS Missing Allow Origin` as illustrated in the following screenshot:
![Screenshot 2023-03-22 at 3 16 25 PM](https://user-images.githubusercontent.com/69568555/226916043-c5e1e0d5-b0c7-4f24-b894-1382b82ecf66.png)

Could you please let me know how to solve that?

**Comment by lunkwill42** [comment]
This seems related to #451 and Uninett/Argus#584.  #451 is still being fixed.  Since you didn't use any of our issue templates, we don't know which versions of the back-end and front-end software you're using.

Likely you will need to adjust the `ARGUS_FRONTEND_URL` variable of the back-end, so it produces a correct CORS policy.

**Comment by hmpf** [comment]
The login-screen doesn't show any versions IIRC, maybe it should.

**Comment by mhmdawnallah** [comment]
@lunkwill42 Yeah I'm using the latest version of master branch in both frontend and backend

**Comment by lunkwill42** [comment]
Alright, @mhmdawnallah, then the CORS bug in the backend should be fixed in your version.  Again, you need to ensure `ARGUS_FRONTEND_URL` is correctly set for your back-end process.

**Comment by podliashanyk** [comment]
@mhmdawnallah #496 is now merged and the misleading _Wrong username or password_ error message is now fixed on master. There is also an open issue on handling CORS errors specifically #498
