### ISSUE TITLE
Consume real-time API from backend

### ISSUE THREAD

**Issue by havfo** [Uninett/Argus-frontend#58]
Depends on https://github.com/Uninett/aas/issues/27

This will allow clients to get alerts in real-time from the backend as soon as they arrive.

**Comment by hmpf** [comment]
While there need to be something to consume, thoughts around what is needed/desired frontend-wise can be added here.

**Comment by hmpf** [comment]
Websockets with channels is implemented in backend, used by frontend. Closing.
