### ISSUE TITLE
Code formatting does not reflect description in README.md 

### ISSUE THREAD

**Issue by jorgenbele** [Uninett/Argus-frontend#70]
The current [README.md](https://github.com/Uninett/aas-frontend/blob/e4445078e12be89dd3c1be00dfc1886361d0959e/README.md#prettier) describes the use of the formatting tool `prettier` as if it is used uniformly throughout the project. This does not seem like it is the case, because running the formatter using default settings on src/ results in +887, -842 (32 files) and a modified version as described in #68 results in +796, -949 (32 files).

There is no description of a configuration, so I conclude that the README.md description is invalid. Use of a formatter is desirable, so how should the project move forward. Should we use it on only new code, on all files we modify, on the entire source tree, or something else?

**Comment by ddabble** [comment]
I vote for reformatting the entire source tree.

Do you have any preferences or opinions, @jorgenbele, @havfo and @hmpf?

**Comment by jorgenbele** [comment]
I also support the proposal of having a single commit reformatting everything using prettier.

**Comment by jorgenbele** [comment]
Done in 4d0f822d993ccf58dbbcbfcc6585941f37dbb61f
