### ISSUE TITLE
timeslots view fails to properly handle multiple days with same start and end time

### ISSUE THREAD

**Issue by jorgenbele** [Uninett/Argus-frontend#78]
When you are creating a time-slot that has more than one day with the same start and end time, for example the following:
![image](https://user-images.githubusercontent.com/1580755/85262693-6f9a3200-b46e-11ea-8db8-8b18c44beaaf.png)

You get the following result:
![image](https://user-images.githubusercontent.com/1580755/85262682-6ad57e00-b46e-11ea-9c5e-b303dcb4d570.png)

Problem:
- Instead of creating a "time interval" with multiple days for the same interval, for example; every mon, tue, wed from 08:15 - 12:00, it will create a new "time interval" for each day resulting in every mon 08:15-12:00, tue 08:15-12:00, wed 08:15-12:00.

**Comment by lunkwill42** [comment]
The example name "Immediately" also doesn't make much sense. We might need to discuss profiles and notifications further IRL to ensure we're all on the same page when it comes to those.
