### ISSUE TITLE
Time everywhere in UI should be 24h

### ISSUE THREAD

**Issue by hmpf** [Uninett/Argus-frontend#80]
Is this 24h time?

![Screenshot_2020-06-23 React App](https://user-images.githubusercontent.com/11956096/85369716-e21e1700-b52d-11ea-8fb9-556025e63217.png)

How are you supposed to create a duration that is 24h.

![Screenshot_2020-06-23 React App(1)](https://user-images.githubusercontent.com/11956096/85369836-1c87b400-b52e-11ea-8583-cf629cf1ee9b.png)

**Comment by jorgenbele** [comment]
The start of day and end of day is defined in the backend here: https://github.com/Uninett/Argus/blob/1bcee6aaeb2e04f2e26b394d349f49bc2a510422/src/aas/notificationprofile/models.py#L61

https://github.com/Uninett/Argus/blob/1bcee6aaeb2e04f2e26b394d349f49bc2a510422/src/aas/notificationprofile/models.py#L60-L62
```python
class TimeInterval(models.Model):
    DAY_START = time.min
    DAY_END = time.max
```

where `time` is imported from `datetime` here:
https://github.com/Uninett/Argus/blob/1bcee6aaeb2e04f2e26b394d349f49bc2a510422/src/aas/notificationprofile/models.py#L2
```python
from datetime import datetime, time
```

Evaluating `time.min` and `time.max` in the python interpreter gives the following:
```
datetime.time(0, 0)
datetime.time(23, 59, 59, 999999)
```
I'm not really sure how this could be solved in the frontend. It could be solved by handling a special case of 00:00 (AM/PM), or by making the range: `start <= x < round_up(end)` such that 11:59 includes 11:59:59:9999.

In addition, what about timezones? I cannot see a way to set timezone, so how does it determine one?

**Comment by hmpf** [comment]
There might be a checkbox with "All day"?
