### ISSUE TITLE
Incident details dialog/modal

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#93]
Clicking on an Incident description in the incident list should open a modal showing fuller details of the incident. I.e. the modal should repeat the information from the incident table entry, but also "everything else" related to the Incident, such as:

* A list/table summarizing the Incident's related Events.
* A list of tags attached to the Incident.
  * Any tag value that can be parsed as an URL should be clickable.
* An interface to add/edit/hyperlink the *ticket url* of the Incident.

**Comment by lunkwill42** [comment]
@jorgenbele I'd say this is all fixed, with *one exception*: The model hyperlinks the "details" URL, *however*, it hyperlinks the relative URL stored in the incident object - it doesn't construct the full, valid URL based on the source system's base url. We should really have this in time for Thursday's demo.

**Comment by lunkwill42** [comment]
Making note of the fact that the incident source's base url is available inline in each Incident object:

```json
[
  {
    "pk": 18,
    "start_time": "2020-09-14T17:06:49.983721+02:00",
    "end_time": "infinity",
    "source": {
      "pk": 1,
      "name": "testnav",
      "type": {
        "name": "nav"
      },
      "user": 2,
      "base_url": "http://localhost:9080/"
    },
    "source_incident_id": "199420",
    "details_url": "/search/event/199420",
    "description": "Link DOWN on A1 at example-sw.example.org (4.kx042)",
    "ticket_url": "",
    "tags": []
  }
]
```

**Comment by hmpf** [comment]
The detail url sent from the backend is now absolute if Source.base_url exisdts. Closing this.
