### ISSUE TITLE
Add acknowledgements list to incident details dialog box

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#94]
Once Uninett/Argus#72 is implemented, the Incident details dialog box should also display a list/table of known acknowledgments related to the Incident.

This list/table should contain:
* Who made the ack
* When the ack was made
* The message string of the ack
* The expiry time of the ack, if set

Expired acks should be distinguished. Suggestion: Use a strikethrough for all text on the ack line.

**Comment by jorgenbele** [comment]
# Status
- [X] List of acks is displayed in the incident details dialog
- [X] Button to submit a new ack is below said list
- [X] Acks contain a message and an optional expiry date
- [ ] Acks that have not expired can be modified to set a new expiry date (in the future I assume)

# Screenshots
## List of acks and create button
![2020-07-29-134710_562x317_scrot](https://user-images.githubusercontent.com/1580755/88796510-12e31300-d1a2-11ea-8e00-0bbf118b7a16.png)
## Writing message and selecting (optional) expiry date
![2020-07-29-134718_488x273_scrot](https://user-images.githubusercontent.com/1580755/88796514-14144000-d1a2-11ea-9ba4-06ba6eed0f05.png)

_Originally posted by @jorgenbele in https://github.com/Uninett/Argus-frontend/issues/95#issuecomment-665618802_

**Comment by lunkwill42** [comment]
Looks good, except for the username thing mentioned in #122 .


>     * [ ]  Acks that have not expired can be modified to set a new expiry date (in the future I assume)

Still waiting for edit function then. Yes, the expiry date/time should always be in the future. **However**, one might want to *expire an old acknowledgement immediately* by putting in today's date.

**Comment by lunkwill42** [comment]
I'm going to close this as accepted, but keep #95 for the seeming lack of editing existing acks.
