### ISSUE TITLE
Add interface to submit Incident Acknowledgements

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#95]
Once Uninett/Argus#72 is implemented, the Incident details dialog box must implement an action button to create and submit a new acknowledgement.

* A user should potentially always be allowed to change the expiry time of a previous acknowledgement, but only if it has not already expired (if an ack has expired, make a new one!).

**Comment by jorgenbele** [comment]
# Status
- [X] List of acks is displayed in the incident details dialog
- [X] Button to submit a new ack is below said list
- [X] Acks contain a message and an optional expiry date
- [ ] Acks that have not expired can be modified to set a new expiry date (in the future I assume)

# Screenshots
## List of acks and create button
![2020-07-29-134710_562x317_scrot](https://user-images.githubusercontent.com/1580755/88796510-12e31300-d1a2-11ea-8e00-0bbf118b7a16.png)
## Writing message and selecting (optional) expiry date
![2020-07-29-134718_488x273_scrot](https://user-images.githubusercontent.com/1580755/88796514-14144000-d1a2-11ea-9ba4-06ba6eed0f05.png)

**Comment by lunkwill42** [comment]
Given that #94 was more about displaying acks, I've closed it, and am pasting my last comment here instead:

>     * [ ]  Acks that have not expired can be modified to set a new expiry date (in the future I assume)

Yes, the expiry date/time should always be in the future. **However**, one might want to *expire an old acknowledgement immediately* by putting in today's date.

**Comment by lunkwill42** [comment]
So I gather we still can't edit the expiry time of an existing acknowledgement. This means that either this issue cannot be closed, or we need to register this as a separate issue to target for post-1.0. What would you prefer, @hmpf ?

**Comment by hmpf** [comment]
New issue, definitely. Zombie issues suck.

**Comment by hmpf** [comment]
Since the adventure will continue in #152 I'm closing this issue.
