### ISSUE TITLE
Add interface to manually resolve an open Incident

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#96]
Once Uninett/Argus#73 is implemented, the frontend must provide the user with a function to manually resolve an open Incident.

For individual Incidents, this can be made accessible through the Incident details dialog box.

Manually closing an incident should not be easy to do by accident. There should also be the option to add a message string, explaining why an Incident was resolved manually.

**Comment by hmpf** [comment]
This is implemented both in backend and frontend, closing.
