### ISSUE TITLE
Support bulk operations on open Incidents list

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#97]
The page that lists open incidents should have UI elements to mark multiple Incidents and run various bulk operations against them:

* Manually resolve the selected Incidents, as described in #96 
* Post the same Acknowledgment for each of the selected Incidents, as described in #95

**Comment by jorgenbele** [comment]
Current state:
- [X] Implement UI elements for marking multiple incidents in the incidents table
- [X] Implement UI elements for actions on multiple selected incidents
- [ ] Implement actions for those actions.

**Comment by lunkwill42** [comment]
I want to *bump* this.

Also important to note is: There should be either a button or checkbox to "select all in page", so the user does not have to click on every single checkbox for large bulk updates.
